 SELECT * FROM sales.customers;
 SELECT * FROM sales.transactions;
 SELECT * FROM sales.products;
 SELECT * FROM sales.markets;
 SELECT count(*) FROM sales.transactions;
 SELECT count(*) FROM sales.customers;
 SELECT * FROM sales.transactions where market_code='Mark001';
 SELECT count(*) FROM sales.transactions where market_code='Mark001';
 SELECT * from sales.transactions where currency="USD";
 SELECT * from sales.transactions limit 5;
 SELECT sales.transactions.*, sales.date.* FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020;
 SELECT SUM(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020 and sales.transactions.currency="INR\r";
 SELECT SUM(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2019;
 SELECT AVG(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020;
 SELECT SUM(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020 and sales.transactions.market_code="Mark001";
 SELECT distinct product_code FROM sales.transactions where market_code='Mark001';
 SELECT SUM(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020 and sales.date.month_name="January" and (sales.transactions.currency="INR\r" or transactions.currency="USD\r");
 SELECT SUM(sales.transactions.sales_amount) FROM sales.transactions INNER JOIN sales.date ON sales.transactions.order_date=sales.date.date where sales.date.year=2020 and sales.date.month_name="January";
DROP DATABASE sales;
CREATE DATABASE sales;
